### PR TITLE
Update foxsay.py meme

### PR DESCRIPTION
**Pull request by gmvsound**
An important question asked :):):):)

### CODE REVIEW

**Comment by gingermuffin** [comment]
Hey 🦊 thank you for the PR! 

Could you please explain me the joke? I don't get it 😭

**Comment by gmvsound** [comment]
It's just a stupid Ashton Kutcher movie where that line is literally the
plot of the whole movie 😂

Gina Victoria
IATSE Local 600 Camera Assistant
www.gmvsound.com

**Comment by gingermuffin** [comment]
Oh 😃 That's lovely!

Is this movie related in some ways to foxes? Maybe we could find some foxish wisdom?

**Comment by gmvsound** [comment]
Right on! I will think of something better 😁

Gina Victoria
IATSE Local 600 Camera Assistant
www.gmvsound.com

**Pull request closed without merging**
